{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.redis (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    resource.dependencies/deployments: "{{ include "common.names.custom" (list . "mirror") }} {{ include "common.names.custom" (list . "proxy") }} {{ include "common.names.custom" (list . "server") }} {{ include "common.names.custom" . }}"
    resource.dependencies/statefulsets: "{{ include "common.names.custom" (list . "builder") }} {{ include "common.names.custom" . }}"
    {{- with $conf.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- $secretData := (lookup "v1" "Secret" .Release.Namespace (include "common.names.custom" .)).data }}
  {{- if $conf.authentication.enabled }}
  {{- $password := randAlphaNum 15 | b64enc }}
  {{- if $secretData }}
  {{- $password = index $secretData "REDIS_PASSWD" }}
  {{- end }}
  REDIS_PASSWD: {{ $password | quote }}
  {{- end }}
  REDIS: {{ "true" | b64enc }}
{{- end }}