name: Release lwfhelm

on:
  push:
    tags:
      - 'v*'
      
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 20

      # 向gh-pages分支推送index.yaml更新数据，需要设置user.name和user.email
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Set up Helm
        uses: azure/setup-helm@v4

      # 构建helm的tgz包，并生成index.yaml，推送到默认的gh-pages分支
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ./charts 
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token 用于身份验证

      - name: Publish Release
        uses: ncipollo/release-action@v1
        if: env.release_exists == 'false'
        with:
          artifacts: ./*.tgz
